<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Awardwell
 * Date: 3/16/13
 * Time: 12:54 PM
 * To change this template use File | Settings | File Templates.
 */

/**
 * @param $term
 * @param $vid
 * @param int $parent
 *
 * function for adding terms that are parent to child relationship centric
 */

function ent_taxonomy_add_term($term, $vid, $parent = 0){

  $t = new stdClass();
  $t->name = $term['name'];
  if (array_key_exists('description', $term)) {
    $t->description = $term['description'];
  }
  $t->parent = $parent;
  $t->vid = $vid;
  if (array_key_exists('weight', $term)) {
    $t->weight = $term['weight'];
  }
  // if exists, update
  if (array_key_exists('tid', $term))
    $t->tid = $term['tid'];

  taxonomy_term_save($t);

  if (isset($term['children'])) {
    foreach ($term['children'] as $child){
      ent_taxonomy_add_term($child, $vid, $t->tid);
    }
  }
  unset($t);
}

function ent_util_menu(){
  $items = array();
  $items['api/formatted-nodes'] = array(
    'title' => 'formatted-api-nodes',
    'page callback' => 'ent_util_node_output',
    'page arguments'  => array('ent_project'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  $items['api/formatted-blog-posts'] = array(
    'title' => 'formatted-blog-posts',
    'page callback' => 'ent_util_node_output',
    'page arguments'  => array('article'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  $items['api/cache-hash/%'] = array(
    'title' => 'cacheHash',
    'page callback' => 'ent_util_cache_hash_output',
    'page arguments'  => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}

function ent_util_cache_hash_output($type){
  $hash = array(
    'key' => variable_get($type.'Hash', 0)
  );
  drupal_json_output($hash);
  die();
}

function ent_util_node_output($type){
  $hash = variable_get($type.'Hash', 0);
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', $type)
  ->propertyCondition('status', NODE_PUBLISHED)
  // ->fieldCondition('field_news_types', 'value', 'spotlight', '=')
  // // See the comment about != NULL above.
  // ->fieldCondition('field_photo', 'fid', 'NULL', '!=')
  // ->fieldCondition('field_faculty_tag', 'tid', $value)
  // ->fieldCondition('field_news_publishdate', 'value', $year . '%', 'like')
  // ->fieldOrderBy('field_photo', 'fid', 'DESC')
  // ->range(0, 10)
  // Run the query as user 1.
  ->addMetaData('account', user_load(1));
  $result = $query->execute();

  if (isset($result['node'])) {
    $node_nids = array_keys($result['node']);
    $nodes = ent_util_clean_up(entity_load('node', $node_nids), $type);
  } 

  $for_consumption = array(
    'key' => $hash,
    'items' => $nodes
  );

  drupal_json_output($for_consumption);
  die();
}

function ent_util_clean_up($nodes, $type){
  $new_nodes = array();
  foreach ($nodes as $key => $node) {
    # code...
    $n_n = $node;
    $n_n = entity_metadata_wrapper('node', $node);
    $terms = array();
    $node->content = $n_n->body->value()['value'];
    if($type == 'ent_project'){
      $node->field_image = file_create_url($n_n->field_image->value()['uri']);
      $sm_img = image_style_url('w375max', $n_n->field_image->value()['uri']);
      $md_img = image_style_url('w768max', $n_n->field_image->value()['uri']);
      $lg_img = image_style_url('w992max', $n_n->field_image->value()['uri']);
      $xl_img = image_style_url('w1280max', $n_n->field_image->value()['uri']);
      $node->responsive_images = array(
        'sm_img' => $sm_img,
        'md_img' => $md_img,
        'lg_img' => $lg_img,
        'xl_img' => $xl_img
      );
      $terms = prune_to_terms(entity_load('taxonomy_term', $node->field_skill_category['und']));
    } elseif($type == 'article'){
      $terms = prune_to_terms(entity_load('taxonomy_term', $node->field_tags['und']));
      $node->summary = $n_n->body->value()['summary'];

    }
    $node->terms = $terms;
    $new_nodes[] = $node;
  }
  return $new_nodes;
}

function ent_util_clean_up_single($node){
  # code...
  $new_node = new stdClass();
  $n_n = $node;
  $n_n = entity_metadata_wrapper('node', $node);
  $type = $node->type;
  $new_node->title = $n_n->label();
  $new_node->content = $n_n->body->value()['value'];
  if($type == 'ent_project'){
    $uri = $n_n->field_image->value()['uri'];
    $sm_img = image_style_url('w375max', $uri);
    $md_img = image_style_url('w768max', $uri);
    $lg_img = image_style_url('w992max', $uri);
    $xl_img = image_style_url('w1280max', $uri);
    $new_node->field_image = array(
          'sm_img' => $sm_img,
          'md_img' => $md_img,
          'lg_img' => $lg_img,
          'xl_img' => $xl_img
    );
    $new_node->field_gallery_images = fix_gallery_images($n_n->field_gallery_image->value());
  }
  return $new_node;
}

function prune_to_terms($raw_terms){
  $terms = array();
  foreach ($raw_terms as $key => $t) {
    $terms[] = array(
      'tid' =>  $t->tid,
      'name' => $t->name
    );
    # code...
  }
  return $terms;
}

function fix_gallery_images($images){
  foreach ($images as $key => $t) {
    $sm_img = image_style_url('w375max', $t['uri']);
    $md_img = image_style_url('w768max', $t['uri']);
    $lg_img = image_style_url('w992max', $t['uri']);
    $xl_img = image_style_url('w1280max', $t['uri']);
    $is[] = array(
      'title' =>  $t['title'],
      'image' => array(
        'sm_img' => $sm_img,
        'md_img' => $md_img,
        'lg_img' => $lg_img,
        'xl_img' => $xl_img
      )
    );
    # code...
  }
  return $is;
}

function ent_util_services_request_postprocess_alter($controller, $args, &$result){
  // preprocess node retrvieval
  if($controller['callback'] === '_node_resource_retrieve'){
    $result = ent_util_clean_up_single($result);
  }
}

function ent_util_node_update($node){
  create_caching_hash($node);
}

function ent_util_node_insert($node){
  create_caching_hash($node);
}

function create_caching_hash($node){
  $type = $node->type;
  $date = new DateTime();
  $ts = $date->getTimestamp();
  $hash = md5($ts);
  switch ($type) {
    case 'ent_project':
      variable_set('ent_projectHash', $hash);
      break;
    case 'article':
      variable_set('articleHash', $hash);
      break;
    default:
      break;
  }
}


function ent_util_image_default_styles() {
  $styles = array();
  $styles['home_page_work_320w_180h'] = array(
      'name' => 'home_page_work_320w_180h',
      'effects' => array(
        6 => array(
          'label' => 'Scale and crop',
          'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
          'effect callback' => 'image_scale_and_crop_effect',
          'dimensions callback' => 'image_resize_dimensions',
          'form callback' => 'image_resize_form',
          'summary theme' => 'image_resize_summary',
          'module' => 'image',
          'name' => 'image_scale_and_crop',
          'data' => array(
            'width' => '320',
            'height' => '180',
          ),
          'weight' => '1',
        ),
      ),
  );
  $styles['home_page_work_480w_270h'] = array(
    'name' => 'home_page_work_480w_270h',
    'effects' => array(
      6 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => '480',
          'height' => '270',
        ),
        'weight' => '1',
      ),
    ),
  );

  $styles['front_page_image'] = array(
    'name' => 'front_page_image',
    'effects' => array(
      6 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_crop',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => '1240',
          'height' => '620',
        ),
        'weight' => '1',
      ),
    ),
  );
  $styles['slide_thumbcrop_image'] = array(
    'name' => 'slide_thumbcrop_image',
    'effects' => array(
      6 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_crop',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => '160',
          'height' => '160',
        ),
        'weight' => '1',
      ),
    ),
  );
  return $styles;
}
